// <auto-generated />
using System;
using EFCore.Observability.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Observability.API.Migrations
{
    [DbContext(typeof(PrimaryDbContext))]
    [Migration("20260228201421_init-creation")]
    partial class initcreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Observability.API.Data.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "ACC001",
                            Amount = 100.50m,
                            CreatedAt = new DateTime(2026, 2, 28, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(7692),
                            DueDate = new DateTime(2026, 3, 30, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(7574),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "ACC002",
                            Amount = 250.00m,
                            CreatedAt = new DateTime(2026, 2, 28, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(7716),
                            DueDate = new DateTime(2026, 3, 15, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(7707),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "ACC003",
                            Amount = 75.25m,
                            CreatedAt = new DateTime(2026, 2, 28, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(7735),
                            DueDate = new DateTime(2026, 4, 14, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(7728),
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("EFCore.Observability.API.Data.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.50m,
                            BillId = 1,
                            PaymentDate = new DateTime(2026, 2, 28, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(8253),
                            TransactionId = "TXN001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 75.25m,
                            BillId = 3,
                            PaymentDate = new DateTime(2026, 2, 28, 22, 14, 19, 23, DateTimeKind.Local).AddTicks(8272),
                            TransactionId = "TXN002"
                        });
                });

            modelBuilder.Entity("EFCore.Observability.API.Data.Payment", b =>
                {
                    b.HasOne("EFCore.Observability.API.Data.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });
#pragma warning restore 612, 618
        }
    }
}
