apiVersion: v1
kind: Service
metadata:
  name: efcore-api
  namespace: dbpoolinsight
  labels:
    app: efcore-api
    app.kubernetes.io/part-of: dbpoolinsight
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: efcore-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP